# Generated by Django 2.0.4 on 2018-05-09 21:48

# Librerias Standard
import datetime

# Librerias Django
import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('password', models.CharField(max_length=128, null=True, verbose_name='Clave')),
                ('last_login', models.DateTimeField(default=datetime.datetime.now, verbose_name='Último inicio de sesión:')),
                ('is_superuser', models.BooleanField(db_index=True, default=False, verbose_name='Super Administrador')),
                ('is_staff', models.BooleanField(db_index=True, default=False, verbose_name='Mantenimiento')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Activo')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Nombre de usuario')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.CharField(db_index=True, max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Persona',
                'db_table': 'auth_user',
                'verbose_name_plural': 'Personas',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
