# Generated by Django 2.1.2 on 2018-11-07 11:35

# Librerias Django
import django.utils.timezone
from django.db import migrations, models

# Librerias desarrolladas por mi
import cuenta.libSobreEscribirImagen
import cuenta.models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_auto_20180702_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='persona',
            name='avatar',
            field=models.ImageField(default='avatar/default_avatar.png', max_length=255, storage=cuenta.libSobreEscribirImagen.SobreEscribirAvatar(), upload_to=cuenta.models.image_path),
        ),
        migrations.AlterField(
            model_name='persona',
            name='cedula_identidad',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='celular',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.CharField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email_secundario',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='first_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='is_staff',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='is_superuser',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='persona',
            name='last_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='letra_cedula_identidad',
            field=models.CharField(choices=[('V', 'V'), ('E', 'E')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='persona',
            name='otros_apellidos',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='otros_nombres',
            field=models.CharField(blank=True, db_index=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
