# Generated by Django 2.2.8 on 2019-12-04 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('fc', models.DateTimeField(auto_now_add=True, null=True)),
                ('fm', models.DateTimeField(auto_now=True, null=True)),
                ('task', models.CharField(max_length=255, verbose_name='Task')),
                ('solve', models.BooleanField(default=False, verbose_name='Solve')),
                ('solve_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Solve date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('uc', models.ForeignKey(blank=True, db_column='uc', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_task_uc', to=settings.AUTH_USER_MODEL)),
                ('um', models.ForeignKey(blank=True, db_column='um', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='task_task_um', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
